### ISSUE TITLE
glue etl job failed on No module named 'tornado'

### ISSUE THREAD

**Issue by zxkane** [awslabs/realtime-fraud-detection-with-gnn-on-dgl#116]
Glue Job of training pipeline failed on below error,

> No module named 'tornado'

### Reproduction Steps

1. clean existing cdk.out if it exists
2. deploy solution into account
3. trigger the training pipeline in step functions

### Error Log

found below error log of glue job execution,

```
2021-05-19 11:32:20,338 ERROR [main] glue.ProcessLauncher (Logging.scala:logError(70)): Error from Python:Traceback (most recent call last):
  File "/tmp/glue-etl.py", line 12, in <module>
    from neptune_python_utils.gremlin_utils import GremlinUtils
  File "/tmp/neptune_python_utils.zip/neptune_python_utils/gremlin_utils.py", line 18, in <module>
    from neptune_python_utils.endpoints import Endpoints
  File "/tmp/neptune_python_utils.zip/neptune_python_utils/endpoints.py", line 18, in <module>
    from tornado.httputil import HTTPHeaders
ModuleNotFoundError: No module named 'tornado'
```

### Environment

  - **CDK CLI Version:** 
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**

### Other

--- 

This is :bug: Bug Report

**Comment by zxkane** [comment]
it’s related to https://github.com/awslabs/amazon-neptune-tools/issues/129, the build script always install the latest `greminpython` which removes dependency `torndo` since [version 3.5.0](https://libraries.io/pypi/gremlinpython/3.5.0).
